
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spring-ribbon-consumer
spring-ribbon-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.tsb.study.springcloud.ribbon.springribbon.consumer.MyRule
server:
  port: 8090