server:
  context-path: /oa
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/ACT?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver