server:
  port: 9000
spring:
  application:
    name: spring-zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
zuul:
  routes:
    sale:
      path: /sale_1/**
      serviceId: spring-zuul-sale